// Generated by CoffeeScript 1.12.2
(function() {
  var aString, areYouHappy, balance, csOutput, largeNumStr, largestNum, name, randNum, randomNum, smallNumStr, smallestNum;

  name = "Erik";

  csOutput = document.getElementById("csoutput");

  csOutput.innerHTML = "Hello " + name + "<br>";

  aString = "I'm a String";

  if (typeof aString === 'string') {
    csOutput.insertAdjacentHTML('beforeend', 'aString is a String<br>');
  }

  largestNum = Number.MAX_VALUE;

  smallestNum = Number.MIN_VALUE;

  largeNumStr = "The largest number is " + largestNum + "<br>";

  smallNumStr = "The smallest number is " + smallestNum + "<br>";

  csOutput.insertAdjacentHTML('beforeend', largeNumStr + '<br>');

  csOutput.insertAdjacentHTML('beforeend', smallNumStr + '<br>');

  areYouHappy = false;

  if (typeof areYouHappy === 'boolean') {
    csOutput.insertAdjacentHTML('beforeend', 'areYouHappy is a Boolean<br>');
  }

  csOutput.insertAdjacentHTML('beforeend', "5 + 2 = " + (5 + 2) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "5 - 2 = " + (5 - 2) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "5 * 2 = " + (5 * 2) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "5 / 2 = " + (5 / 2) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "5 % 2 = " + (5 % 2) + "<br>");

  balance = 1563.87;

  csOutput.insertAdjacentHTML('beforeend', "Monthly Payment = " + ((balance / 12).toFixed(2)) + "<br>");

  randNum = 5;

  csOutput.insertAdjacentHTML('beforeend', "randNum++ = " + (randNum++) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "++randNum = " + (++randNum) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "randNum-- = " + (randNum--) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "--randNum = " + (--randNum) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "randNum += 5 " + (randNum += 5) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "3 + 2 * 5 = " + (3 + 2 * 5) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "(3 + 2) * 5 = " + ((3 + 2) * 5) + "<br>");

  randomNum = Math.floor(Math.random() * 100) + 1;

  csOutput.insertAdjacentHTML('beforeend', "Random Number = " + randomNum + "<br>");

}).call(this);
