// Generated by CoffeeScript 1.12.2
(function() {
  var csOutput, factorial, getRandNum, helloFunc, movieRank, sumNums,
    slice = [].slice;

  csOutput = document.getElementById("csoutput");

  helloFunc = function(name) {
    return "Hello " + name;
  };

  csOutput.insertAdjacentHTML('beforeend', (helloFunc("Erik")) + "<br>");

  getRandNum = function() {
    return Math.floor(Math.random() * 100) + 1;
  };

  csOutput.insertAdjacentHTML('beforeend', "Random number: " + (getRandNum()) + "<br>");

  sumNums = function() {
    var i, len, sum, vars, x;
    vars = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    sum = 0;
    for (i = 0, len = vars.length; i < len; i++) {
      x = vars[i];
      sum += x;
    }
    return sum;
  };

  csOutput.insertAdjacentHTML('beforeend', "Sum: " + (sumNums(1, 2, 3, 4, 5)) + "<br>");

  movieRank = function(stars) {
    if (stars == null) {
      stars = 1;
    }
    if (stars <= 2) {
      return "Bad";
    } else {
      return "Good";
    }
  };

  csOutput.insertAdjacentHTML('beforeend', "Movie Rank: " + (movieRank(4)) + "<br>");

  factorial = function(x) {
    if (x < 0) {
      return 0;
    }
    if (x === 0 || x === 1) {
      return 1;
    }
    return x * factorial(x - 1);
  };

  csOutput.insertAdjacentHTML('beforeend', "Factorial of 4: " + (factorial(4)) + "<br>");

}).call(this);
